Repository Paws-Time/PawsTimeProject-Back, pull requests merged in 2024-12, with the labels that each got.

#2 feat: create baseEntity
  src/main/java/com/pawstime/pawstime/PawstimeApplication.java
  src/main/java/com/pawstime/pawstime/global/entity/BaseEntity.java
Labels: enhancement

#9 feat:create entity userrole
  src/main/java/com/pawstime/pawstime/domain/Role/entity/Role.java
  src/main/java/com/pawstime/pawstime/domain/Role/entity/repository/RoleRepository.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/repository/UserRepository.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/domain/user/service/create/CreateUserService.java
  src/main/java/com/pawstime/pawstime/domain/user/service/read/ReadUserService.java
  src/main/java/com/pawstime/pawstime/domain/userrole/entity/UserRole.java
  src/main/java/com/pawstime/pawstime/domain/userrole/entity/repository/UserRoleRepository.java
  src/main/java/com/pawstime/pawstime/global/config/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/pawstime/pawstime/global/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/pawstime/pawstime/global/config/security/user/service/CustomUserDetailsService.java
  src/main/java/com/pawstime/pawstime/global/dto/ErrorResponseDto.java
  src/main/java/com/pawstime/pawstime/web/api/user/UserApiController.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/request/LoginUserRequestDto.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/request/UserCreateRequestDto.java
Labels: WIP

#11 feat: docker에 이미지 빌드 및 푸시
  Dockerfile
  build.gradle
  docker-compose.yml
  docker/docker-compose.yaml
  docker/my.cnf
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/board/dto/resp/GetBoardRespDto.java
  src/main/java/com/pawstime/pawstime/domain/board/facade/BoardFacade.java
  src/main/java/com/pawstime/pawstime/domain/board/service/ReadBoardService.java
  src/main/resources/application.yml
Labels: enhancement

#16 feat: board 목록 조회 기능
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/board/entity/repository/BoardRepository.java
  src/main/java/com/pawstime/pawstime/domain/board/facade/BoardFacade.java
  src/main/java/com/pawstime/pawstime/domain/board/service/ReadBoardService.java
  src/main/java/com/pawstime/pawstime/global/config/swagger/SwaggerConfig.java
  src/main/resources/application-local.yml
Labels: enhancement

#22 feat: deleteBoard를 이용해 게시판 논리 삭제 기능구현
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/board/entity/Board.java
  src/main/java/com/pawstime/pawstime/domain/board/facade/BoardFacade.java
  src/main/java/com/pawstime/pawstime/global/entity/BaseEntity.java
Labels: enhancement

#25 Feat/update post
  src/main/java/com/pawstime/pawstime/domain/board/service/ReadBoardService.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/CreatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/UpdatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/ReadPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/UpdatePostService.java
  src/main/java/com/pawstime/pawstime/domain/user/controller/UserController.java
Labels: enhancement

#27 feat: updateBoard
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/board/dto/req/UpdateBoardReqDto.java
  src/main/java/com/pawstime/pawstime/domain/board/entity/Board.java
  src/main/java/com/pawstime/pawstime/domain/board/facade/BoardFacade.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: enhancement

#28 feat:delete post
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/CreatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/UpdatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/DeletePostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/ReadPostService.java
  src/main/java/com/pawstime/pawstime/global/entity/BaseEntity.java
Labels: enhancement

#31 feaet:게시글 상세 조회
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/resp/GetDetailPostRespDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/GetDetailPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/ReadPostService.java
Labels: enhancement

#34 style: 응답 구조 정의 및 게시판 엔티티에 적용
  docker-compose.yml
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/board/dto/req/CreateBoardReqDto.java
  src/main/java/com/pawstime/pawstime/domain/board/dto/req/UpdateBoardReqDto.java
  src/main/java/com/pawstime/pawstime/domain/board/dto/resp/GetBoardRespDto.java
  src/main/java/com/pawstime/pawstime/domain/board/facade/BoardFacade.java
  src/main/java/com/pawstime/pawstime/global/common/ApiResponse.java
  src/main/java/com/pawstime/pawstime/global/enums/Status.java
  src/main/java/com/pawstime/pawstime/global/exception/CustomException.java
  src/main/java/com/pawstime/pawstime/global/exception/DuplicateException.java
  src/main/java/com/pawstime/pawstime/global/exception/InvalidException.java
  src/main/java/com/pawstime/pawstime/global/exception/NotFoundException.java
Labels: style

#36 refactor: 게시글 조회 쿼리의 sort 파라미터 처리 방식 개선
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/repository/PostRepository.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/GetListPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/ReadPostService.java
Labels: bug, enhancement

#38 feat: createComment
  src/main/java/com/pawstime/pawstime/domain/board/facade/BoardFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/dto/req/CreateCommentReqDto.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/Comment.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/repository/CommentRepository.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/CreateCommentService.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/ReadCommentService.java
  src/main/java/com/pawstime/pawstime/global/config/web/WebConfig.java
Labels: enhancement

#40 refact:post 응답 구조 개선
  src/main/java/com/pawstime/pawstime/domain/board/service/ReadBoardService.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/CreatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/repository/PostRepository.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/DeletePostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/GetDetailPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/GetListPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/ReadPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/UpdatePostService.java
Labels: enhancement

#48 fix: httpStatus 응답코드 수정
  docker-compose.yml
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/dto/resp/GetCommentRespDto.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/repository/CommentRepository.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/ReadCommentService.java
  src/main/java/com/pawstime/pawstime/global/common/ApiResponse.java
  src/main/java/com/pawstime/pawstime/global/config/web/WebConfig.java
  src/main/java/com/pawstime/pawstime/global/enums/Status.java
Labels: bug

#46 feat: 댓글 전체 목록 조회 기능 구현
  docker-compose.yml
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/dto/resp/GetCommentRespDto.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/repository/CommentRepository.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/ReadCommentService.java
  src/main/java/com/pawstime/pawstime/global/config/web/WebConfig.java
Labels: enhancement

#49 feat: 특정 게시글에 달린 댓글 목록만 조회하는 기능 구현
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/board/facade/BoardFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/repository/CommentRepository.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/ReadCommentService.java
  src/main/java/com/pawstime/pawstime/global/common/ApiResponse.java
  src/main/java/com/pawstime/pawstime/global/enums/Status.java
Labels: enhancement

#52 feat: 댓글 삭제 기능 구현
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/ReadCommentService.java
Labels: enhancement

#55 refact:specificationã 을 통한 정렬 및 검색기능 구현
  src/main/java/com/pawstime/pawstime/domain/Role/entity/repository/RoleRepository.java
  src/main/java/com/pawstime/pawstime/domain/board/entity/repository/BoardRepository.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/repository/PostRepository.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/GetListPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/PostSpecification.java
  src/main/java/com/pawstime/pawstime/domain/role/entity/Role.java
  src/main/java/com/pawstime/pawstime/domain/role/entity/repository/RoleRepository.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
  src/main/java/com/pawstime/pawstime/domain/user/service/create/CreateUserService.java
  src/main/java/com/pawstime/pawstime/domain/user/service/dto/CustomUserInfoDto.java
  src/main/java/com/pawstime/pawstime/domain/userrole/entity/UserRole.java
Labels: enhancement

#56 좋아요:기능 추가
  src/main/java/com/pawstime/pawstime/domain/like/entity/Like.java
  src/main/java/com/pawstime/pawstime/domain/like/entity/repository/LikeRepository.java
  src/main/java/com/pawstime/pawstime/domain/like/facade/LikeFacade.java
  src/main/java/com/pawstime/pawstime/domain/like/service/LikeService.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/CreatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/PostSpecification.java
Labels: enhancement

#59 feat/delete_category
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/CreatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/UpdatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/resp/GetListPostRespDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/GetListPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/PostSpecification.java
Labels: enhancement

#61 feat:게시글 이미지 엔티티 생성
  build.gradle
  src/main/java/com/pawstime/pawstime/domain/image/entity/Image.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
Labels: enhancement

#63 Feat/update comment
  build.gradle
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/dto/req/UpdateCommentReqDto.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/repository/CommentRepository.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/image/entity/Image.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/CreatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/CreatePostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/S3Service.java
  src/main/resources/application.yml
Labels: enhancement

#65 feat: jwt-security를 활용한 회원가입, 로그인, 로그아웃 기능 구현
  build.gradle
  src/main/java/com/pawstime/pawstime/domain/like/entity/repository/LikeRepository.java
  src/main/java/com/pawstime/pawstime/domain/like/service/LikeService.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/role/entity/Role.java
  src/main/java/com/pawstime/pawstime/domain/role/entity/repository/RoleRepository.java
  src/main/java/com/pawstime/pawstime/domain/tokenBlacklist/entity/TokenBlacklist.java
  src/main/java/com/pawstime/pawstime/domain/tokenBlacklist/entity/repository/TokenBlacklistRepository.java
  src/main/java/com/pawstime/pawstime/domain/tokenBlacklist/service/TokenBlacklistService.java
  src/main/java/com/pawstime/pawstime/domain/user/controller/UserController.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/repository/UserRepository.java
  src/main/java/com/pawstime/pawstime/domain/user/enums/Role.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/domain/user/service/create/CreateUserService.java
  src/main/java/com/pawstime/pawstime/domain/user/service/dto/CustomUserInfoDto.java
  src/main/java/com/pawstime/pawstime/domain/user/service/read/ReadUserService.java
  src/main/java/com/pawstime/pawstime/domain/userrole/entity/UserRole.java
  src/main/java/com/pawstime/pawstime/domain/userrole/entity/repository/UserRoleRepository.java
  src/main/java/com/pawstime/pawstime/global/config/security/SecurityConfig.java
  src/main/java/com/pawstime/pawstime/global/dto/ErrorResponseDto.java
  src/main/java/com/pawstime/pawstime/global/enums/ResponseCode.java
  src/main/java/com/pawstime/pawstime/global/exception/UnauthorizedException.java
  src/main/java/com/pawstime/pawstime/global/handler/CustomExceptionHandler.java
  src/main/java/com/pawstime/pawstime/global/jwt/filter/JwtFilter.java
  src/main/java/com/pawstime/pawstime/global/jwt/util/JwtUtil.java
  src/main/java/com/pawstime/pawstime/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/pawstime/pawstime/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/pawstime/pawstime/global/security/user/CustomUserDetails.java
  src/main/java/com/pawstime/pawstime/global/security/user/service/CustomUserDetailsService.java
  src/main/java/com/pawstime/pawstime/web/api/user/UserApiController.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/req/LoginUserReqDto.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/req/UserCreateReqDto.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/resp/Response.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: enhancement

#71 refactor: user 응답 구조 통일, 예외 처리
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/global/exception/ForbiddenException.java
  src/main/java/com/pawstime/pawstime/web/api/user/UserApiController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: enhancement

#72 feat: 지역별 동물병원 목록 조회
  src/main/java/com/pawstime/pawstime/domain/board/controller/BoardController.java
  src/main/java/com/pawstime/pawstime/domain/board/dto/req/CreateBoardReqDto.java
  src/main/java/com/pawstime/pawstime/domain/board/entity/Board.java
  src/main/java/com/pawstime/pawstime/domain/board/entity/repository/BoardRepository.java
  src/main/java/com/pawstime/pawstime/domain/board/service/CreateBoardService.java
  src/main/java/com/pawstime/pawstime/domain/board/service/ReadBoardService.java
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/dto/resp/GetCommentRespDto.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/ReadCommentService.java
  src/main/java/com/pawstime/pawstime/domain/image/entity/Image.java
  src/main/java/com/pawstime/pawstime/domain/info/controller/InfoController.java
  src/main/java/com/pawstime/pawstime/domain/info/dto/resp/GetHospitalInfoRespDto.java
  src/main/java/com/pawstime/pawstime/domain/info/entity/Info.java
  src/main/java/com/pawstime/pawstime/domain/info/entity/repository/InfoRepository.java
  src/main/java/com/pawstime/pawstime/domain/info/facade/InfoFacade.java
  src/main/java/com/pawstime/pawstime/domain/info/service/ReadHospitalInfoService.java
  src/main/java/com/pawstime/pawstime/domain/like/entity/Like.java
  src/main/java/com/pawstime/pawstime/domain/like/entity/repository/LikeRepository.java
  src/main/java/com/pawstime/pawstime/domain/like/service/LikeService.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/CreatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/req/UpdatePostReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/resp/GetDetailPostRespDto.java
  src/main/java/com/pawstime/pawstime/domain/post/dto/resp/GetListPostRespDto.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/Post.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/repository/PostRepository.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/CreatePostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/GetListPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/PostSpecification.java
  src/main/java/com/pawstime/pawstime/domain/post/service/ReadPostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/S3Service.java
  src/main/java/com/pawstime/pawstime/domain/post2/controller/Post2Controller.java
  src/main/java/com/pawstime/pawstime/domain/post2/dto/req/CreatePost2ReqDto.java
  src/main/java/com/pawstime/pawstime/domain/post2/entity/Post2.java
  src/main/java/com/pawstime/pawstime/domain/post2/entity/repository/Post2Repository.java
  src/main/java/com/pawstime/pawstime/domain/post2/facade/Post2Facade.java
  src/main/java/com/pawstime/pawstime/domain/post2/service/CreatePost2Service.java
  src/main/java/com/pawstime/pawstime/domain/post2/service/ReadPost2Service.java
  src/main/java/com/pawstime/pawstime/domain/tokenBlacklist/entity/TokenBlacklist.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/global/config/security/SecurityConfig.java
  src/main/java/com/pawstime/pawstime/global/handler/CustomExceptionHandler.java
  src/main/java/com/pawstime/pawstime/web/api/user/UserApiController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: enhancement
