Repository Paws-Time/PawsTimeProject-Back, pull requests merged in 2025-03, with the labels that each got.

#102 feat:add LikesCount to Detail Post
  src/main/java/com/pawstime/pawstime/domain/post/dto/resp/GetDetailPostRespDto.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/entity/ProfileImg.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
Labels: enhancement

#104 feat:create profileImg Entity
  src/main/java/com/pawstime/pawstime/domain/profileImg/entity/ProfileImg.java
Labels: enhancement

#107 feat:add default profile img to user
  src/main/java/com/pawstime/pawstime/domain/image/entity/Image.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/entity/ProfileImg.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/entity/repository/ProfileRepository.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
  src/main/java/com/pawstime/pawstime/domain/user/service/create/CreateUserService.java
  src/main/java/com/pawstime/pawstime/domain/user/service/dto/CustomUserInfoDto.java
  src/main/resources/static/profile-img.jpg
Labels: enhancement

#109 Feat:Update Profile Image
  src/main/java/com/pawstime/pawstime/aws/s3/config/S3Config.java
  src/main/java/com/pawstime/pawstime/aws/s3/service/S3Service.java
  src/main/java/com/pawstime/pawstime/domain/image/service/UpdateImageService.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/controller/ProfileImgController.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/entity/ProfileImg.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/entity/repository/ProfileRepository.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/facade/ProfileImgFacade.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/service/CreateProfileImgService.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/service/ReadProfileImgService.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/repository/UserRepository.java
  src/main/resources/application-dev.yml
Labels: enhancement

#114 Feat:탈퇴한 유저 소프트 딜리트 적용 및 탈퇴한 유저 로그인 방지 및 즉시 로그아웃 처리
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/create/CreatePostService.java
  src/main/java/com/pawstime/pawstime/domain/post/service/read/ReadPostService.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/repository/UserRepository.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/domain/user/service/read/ReadUserService.java
  src/main/java/com/pawstime/pawstime/web/api/user/UserController.java
Labels: enhancement

#117 feat: 마이페이지에서 사용자가 작성한 게시글 및 댓글 조회 기능 추가
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/dto/resp/GetCommentRespDto.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/repository/CommentRepository.java
  src/main/java/com/pawstime/pawstime/domain/comment/facade/CommentFacade.java
  src/main/java/com/pawstime/pawstime/domain/comment/service/ReadCommentService.java
  src/main/java/com/pawstime/pawstime/domain/post/controller/PostController.java
  src/main/java/com/pawstime/pawstime/domain/post/entity/repository/PostRepository.java
  src/main/java/com/pawstime/pawstime/domain/post/facade/PostFacade.java
  src/main/java/com/pawstime/pawstime/domain/post/service/read/ReadPostService.java
  src/main/java/com/pawstime/pawstime/global/config/security/SecurityConfig.java
  src/main/resources/application-dev.yml
Labels: enhancement

#121 feat: 마이페이지에서 유저의 닉네임 및 비밀번호 변경 기능 구현
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/domain/user/service/create/CreateUserService.java
  src/main/java/com/pawstime/pawstime/global/config/security/SecurityConfig.java
  src/main/java/com/pawstime/pawstime/web/api/user/UserController.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/req/UpdateNickReqDto.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/req/UpdatePasswordReqDto.java
Labels: enhancement

#120 fix:Login issue occurring after user soft delete
  src/main/java/com/pawstime/pawstime/domain/profileImg/controller/ProfileImgController.java
  src/main/java/com/pawstime/pawstime/domain/profileImg/service/ReadProfileImgService.java
  src/main/java/com/pawstime/pawstime/domain/user/entity/User.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/resources/application-dev.yml
Labels: bug

#123 refactor: 닉네임 중복 확인 기능 추가
  src/main/java/com/pawstime/pawstime/domain/user/entity/repository/UserRepository.java
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/domain/user/service/read/ReadUserService.java
Labels: refactor

#124 fix: 댓글 조회 기능 수정
  src/main/java/com/pawstime/pawstime/domain/comment/controller/CommentController.java
  src/main/java/com/pawstime/pawstime/domain/comment/entity/repository/CommentRepository.java
Labels: bug

#126 feat: 비밀번호 찾기 기능 추가 (이메일 + 닉네임으로 사용자 찾기, 비밀번호 변경)
  src/main/java/com/pawstime/pawstime/domain/user/facade/UserFacade.java
  src/main/java/com/pawstime/pawstime/global/config/security/SecurityConfig.java
  src/main/java/com/pawstime/pawstime/web/api/user/UserController.java
  src/main/java/com/pawstime/pawstime/web/api/user/dto/req/ResetPasswordReqDto.java
Labels: enhancement
